name = "dpp-sync-worker-dev"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Secrets will be set via `wrangler secret put`
# GOOGLE_SERVICE_ACCOUNT = "..."
# SYNC_ACCESS_TOKEN = "..."

[[kv_namespaces]]
binding = "SYNC_KV_DEV"
id = "f125d48544f74a2a902167be60f4d4da"
preview_id = "yyyy"
